spring.application.name=ticket-tracking-system
spring.datasource.url=jdbc:postgresql://localhost:5433/TrackTicket_db
spring.datasource.username=hellouser
spring.datasource.password=hellopassword
spring.datasource.driver-class-name=org.postgresql.Driver




